"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpLeft, ArrowUpRight, AudioLines, BookOpen, BriefcaseBusiness, Check, ChevronLeft, ChevronRight, CircleHelp, Compass, Globe2, GraduationCap, Headphones, Heart, MapPin, MessageCircle, Mic, MicOff, MoreHorizontal, Phone, PhoneOff, Plane, Search, Send, Settings2, ShieldCheck, Sparkles, Volume2, X } from "lucide-react";
import VoiceOrb from "./VoiceOrb";
import { useVoice } from "@/hooks/useVoice";

type Tab = "home" | "programs" | "centers";
type Goal = "general" | "career" | "travel" | "study" | "confidence";
type ChatMessage = { role: "user" | "assistant"; content: string };
type Knowledge = { verified_at: string; programs: { id: string; name: string; ar: string; en: string; description_ar: string; description_en: string; features_ar: string[]; features_en: string[]; url: string }[]; centers: { name: string; name_en: string; city: string; city_en: string; address: string; phone: string }[]; sources: { title: string; url: string }[] };
const goals = [ { id: "career", ar: "أطوّر مسيرتي", en: "Grow my career", icon: BriefcaseBusiness }, { id: "study", ar: "أنجح بدراستي", en: "Succeed in my studies", icon: GraduationCap }, { id: "travel", ar: "أسافر بثقة", en: "Travel with confidence", icon: Plane }, { id: "confidence", ar: "أتكلم بطلاقة", en: "Speak with confidence", icon: MessageCircle } ] as const;

function Wave({ small = false }: { small?: boolean }) { return <span className={`wave ${small ? "small" : ""}`} aria-hidden="true">{[24, 42, 61, 39, 72, 50, 28].map((height, i) => <i key={i} style={{ height: `${height}%`, animationDelay: `${i * .14}s` }} />)}</span>; }

export default function HalaApp() {
  const [language, setLanguage] = useState<"ar" | "en">("ar");
  const [preferencesReady, setPreferencesReady] = useState(false);
  const [tab, setTab] = useState<Tab>("home");
  const [goal, setGoal] = useState<Goal>("general");
  const [modal, setModal] = useState<"chat" | "settings" | "transcript" | "about" | null>(null);
  const [knowledge, setKnowledge] = useState<Knowledge | null>(null);
  const [loadError, setLoadError] = useState(false);
  const [search, setSearch] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [draft, setDraft] = useState("");
  const [chatBusy, setChatBusy] = useState(false);
  const [chatError, setChatError] = useState("");
  const dialog = useRef<HTMLDialogElement>(null);
  const chatBottom = useRef<HTMLDivElement>(null);
  const voice = useVoice(language, goal);
  const ar = language === "ar";
  const t = (a: string, e: string) => ar ? a : e;
  const Arrow = ar ? ArrowLeft : ArrowRight;
  const Outward = ar ? ArrowUpLeft : ArrowUpRight;
  const Chevron = ar ? ChevronLeft : ChevronRight;
  const busy = voice.status !== "idle";
  const statusLabel = { idle: t("جاهزة أسمعك", "Ready when you are"), connecting: t("لحظة، نتّصل…", "Connecting…"), listening: voice.muted ? t("الميكروفون مكتوم", "Microphone muted") : t("أسمعك… خذ راحتك", "Listening… take your time"), thinking: t("أفكّر معك…", "Thinking with you…"), speaking: t("هلا تتكلم…", "Hala is speaking…") }[voice.status];

  async function loadKnowledge() { setLoadError(false); try { const response = await fetch("/api/knowledge"); if (!response.ok) throw new Error(); setKnowledge(await response.json()); } catch { setLoadError(true); } }
  useEffect(() => { void loadKnowledge(); try { const saved = JSON.parse(localStorage.getItem("hala-preferences") || "{}"); if (["ar", "en"].includes(saved.language)) setLanguage(saved.language); if (["general", ...goals.map(g => g.id)].includes(saved.goal)) setGoal(saved.goal); } catch { /* Private browsing can disable storage. */ } setPreferencesReady(true); }, []);
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = ar ? "rtl" : "ltr"; if (preferencesReady) { try { localStorage.setItem("hala-preferences", JSON.stringify({ language, goal })); } catch {} } }, [language, goal, ar, preferencesReady]);
  useEffect(() => { if (modal && !dialog.current?.open) dialog.current?.showModal(); else if (!modal) dialog.current?.close(); }, [modal]);
  useEffect(() => { chatBottom.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, chatBusy, voice.transcript]);

  async function sendChat(text = draft) {
    if (!text.trim() || chatBusy) return;
    setModal("chat"); setDraft(""); setChatError("");
    const next: ChatMessage[] = [...messages, { role: "user", content: text.trim() }];
    setMessages(next); setChatBusy(true);
    try {
      const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next.slice(-23), language, goal }), signal: AbortSignal.timeout(50000) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || "Hala is unavailable.");
      setMessages([...next, { role: "assistant", content: data.reply }]);
    } catch (error) { setChatError(error instanceof Error ? error.message : t("تعذّر الاتصال. جرّب مرة ثانية.", "Could not connect. Please try again.")); setMessages(messages); setDraft(text); }
    finally { setChatBusy(false); }
  }

  const changeLanguage = () => { if (busy) voice.stop(); setLanguage(ar ? "en" : "ar"); };
  const nav = [ { id: "home", label: t("تكلّم مع هلا", "Talk to Hala"), icon: AudioLines }, { id: "programs", label: t("اكتشف برامجنا", "Our programs"), icon: BookOpen }, { id: "centers", label: t("مراكزنا", "Our centers"), icon: MapPin } ] as const;

  return <div className="app-shell" dir={ar ? "rtl" : "ltr"}>
    <aside className="sidebar">
      <a href="https://wallstreetenglish.edu.sa/" target="_blank" rel="noreferrer" className="brand"><img src="/wse-logo.webp" alt="Wall Street English" /></a>
      <div className="workspace-label">YOUR NEXT CHAPTER</div>
      <nav>{nav.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={`nav-item ${tab === item.id ? "selected" : ""}`} aria-current={tab === item.id ? "page" : undefined}><item.icon size={20} /><span>{item.label}</span>{tab === item.id && <span className="nav-dot" />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="little-note"><span className="note-spark"><Sparkles size={21} /></span><h3>{t("خطوة صغيرة، فرق كبير.", "Small steps. Big possibilities.")}</h3><p>{t("كل محادثة تقرّبك من النسخة الواثقة منك.", "Every conversation brings you closer to a more confident you.")}</p><span className="note-line" /></div><button className="nav-item" onClick={() => setModal("about")}><CircleHelp size={19} />{t("عن هلا", "About Hala")}</button><div className="sidebar-footer"><span className="saudi-dot" />{t("مصمّمة لك، في السعودية", "Made for you, in Saudi Arabia")}<span>SA</span></div></div>
    </aside>

    <div className="main-shell">
      <header className="topbar"><div className="breadcrumb"><span>Hala</span><span>/</span>{nav.find(n => n.id === tab)?.label}</div><a className="mobile-brand" href="https://wallstreetenglish.edu.sa/" target="_blank" rel="noreferrer"><img src="/wse-logo.webp" alt="Wall Street English" /></a><div className="top-actions"><span className="demo-badge">{t("تجربة هلا", "HALA DEMO")}</span><button className="language-button" onClick={changeLanguage} aria-label={t("Switch to English", "التبديل للعربية")}><Globe2 size={17} />{ar ? "English" : "العربية"}</button><button className="icon-button settings-button" onClick={() => setModal("settings")} aria-label={t("الإعدادات", "Settings")}><Settings2 size={18} /></button></div></header>

      <main>
        {tab === "home" && <>
          <section className="page-heading"><div className="eyebrow"><span />{t("بداية جديدة، احتمالات أكبر", "A NEW CHAPTER STARTS WITH YOU")}</div><h1>{t("يا هلا، خلّنا نبدأ", "A little hello.")} <span className="accent-word">{t("بمحادثة.", "A world of possibility.")}</span><span className="greeting-star">✳</span></h1><p>{t("أنا هلا، رفيقتك في رحلة الإنجليزية. نسولف، نتعلّم، ونلقى اللي يناسبك.", "I’m Hala, your English learning companion. Let’s talk, learn, and find your way forward.")}</p></section>
          <div className="home-grid">
            <section className={`voice-card ${voice.status}`} aria-label={t("المحادثة الصوتية مع هلا", "Voice conversation with Hala")}>
              <div className="voice-card-top"><span className="live-badge"><span />{busy ? t("محادثة مباشرة", "LIVE CONVERSATION") : t("هلا معك", "HERE FOR YOU")}</span><button className="glass-icon" onClick={() => setModal("about")} aria-label={t("معلومات عن المحادثة", "About voice conversations")}><MoreHorizontal size={22} /></button></div>
              <VoiceOrb status={voice.status} muted={voice.muted} />
              <div className="voice-copy"><h2>{busy ? statusLabel : t("صوتك، بداية رحلتك.", "Your voice. Your first step.")}</h2><p>{busy ? t("تكلم بطبيعتك، وتقدر تقاطعني بأي وقت.", "Speak naturally. You can interrupt me anytime.") : t("سولف معي بالعربي، أو جرّب إنجليزيتك. أنا معك.", "Chat in Arabic, or try your English. I’m right here.")}</p></div>
              <div className="voice-actions">{!busy ? <button className="start-button" onClick={() => void voice.start()}><Mic size={20}/>{t("يلا، نتكلم", "Let’s talk")}<Arrow size={19}/></button> : <div className="call-controls"><button className={`call-icon ${voice.muted ? "muted" : ""}`} disabled={!voice.active} onClick={voice.toggleMute} aria-label={voice.muted ? t("تشغيل الميكروفون", "Unmute") : t("كتم الميكروفون", "Mute")}>{voice.muted ? <MicOff size={21}/> : <Mic size={21}/>}</button><button className="end-button" onClick={voice.stop}><PhoneOff size={19}/>{voice.status === "connecting" ? t("إلغاء الاتصال", "Cancel") : t("إنهاء", "End")}</button><button className="call-icon" onClick={() => setModal("transcript")} aria-label={t("نص المحادثة", "Transcript")}><MessageCircle size={21}/></button></div>}
                {busy ? <span className="call-timer" dir="ltr">{`${Math.floor(voice.seconds / 60)}`.padStart(2,"0")}:{`${voice.seconds % 60}`.padStart(2,"0")} <span> / 10:00</span></span> : <span className="start-hint"><Headphones size={13}/>{t("خذ راحتك… ما فيه إجابة غلط", "No pressure. Just a conversation.")}</span>}
              </div>
              {voice.playBlocked && <button className="audio-retry" onClick={voice.resumeAudio}><Volume2 size={16}/>{t("اضغط لتسمع هلا", "Tap to hear Hala")}</button>}
              <div className="voice-card-footer"><span><ShieldCheck size={14}/>{t("أنت تتحكّم بالميكروفون", "You control your microphone")}</span><span>{t("صوت بالذكاء الاصطناعي", "AI-generated voice")}</span></div>
            </section>

            <aside className="journey-column"><section className="goals-card"><div className="section-kicker"><Compass size={17}/>{t("رحلتك تبدأ منك", "YOUR JOURNEY, YOUR WAY")}</div><h2>{t("وش ودّك تحقق؟", "What’s your next chapter?")}</h2><p>{t("اختَر هدفك، وخلّنا نلقى طريقك له.", "Pick a goal. We’ll find your way there.")}</p><div className="goal-list">{goals.map(item => <button key={item.id} disabled={busy} className={`goal-option ${goal === item.id ? "active" : ""}`} onClick={() => setGoal(goal === item.id ? "general" : item.id)} aria-pressed={goal === item.id}><span className={`goal-icon ${item.id}`}><item.icon size={19}/></span><span>{ar ? item.ar : item.en}</span>{goal === item.id ? <Check size={18}/> : <Chevron size={16}/>}</button>)}</div>{busy && <small>{t("غيّر هدفك بعد المحادثة", "Change your goal after this call")}</small>}</section>
              <button className="text-card" onClick={() => setModal("chat")}><span className="text-card-icon"><MessageCircle size={23}/></span><div><h3>{t("تفضّل الكتابة؟", "More of a texter?")}</h3><p>{t("نفس هلا، بطريقتك.", "Same Hala. Your kind of conversation.")}</p></div><Outward size={20}/></button>
            </aside>
          </div>
          {voice.error && <div className="error-notice" role="alert"><span>{voice.error}</span><button onClick={voice.clearError} aria-label={t("إغلاق التنبيه", "Dismiss error")}><X size={17}/></button></div>}
          <section className="starters-section"><div className="section-heading"><h2>{t("ما تدري من وين تبدأ؟", "Not sure where to start?")}</h2><span>{t("جرّب تسأل هلا", "A LITTLE INSPIRATION")}</span></div><div className="starter-grid">{[{ icon: MessageCircle, a: "أبي أتكلم إنجليزي بثقة", e: "I want to speak English confidently", tone: "peach" }, { icon: BookOpen, a: "وش البرنامج اللي يناسبني؟", e: "Which program is right for me?", tone: "blue" }, { icon: BriefcaseBusiness, a: "ساعديني أستعد لمقابلة عمل", e: "Help me prepare for a job interview", tone: "mint" }].map(item => <button className="starter" key={item.e} onClick={() => void sendChat(t(item.a,item.e))}><span className={`starter-icon ${item.tone}`}><item.icon size={19}/></span><span>{t(item.a,item.e)}</span><Outward size={17}/></button>)}</div></section>
          <section className="full-access-strip"><div className="strip-illustration"><BookOpen size={31}/><span>+</span><Globe2 size={32}/></div><div className="strip-copy"><span>LEARN YOUR WAY</span><h3>{t("أونلاين أو في المركز. المستقبل لك.", "Online or in-center. Your future, your way.")}</h3><p>{t("تعرّف على Full Access وخيارات التعلّم المرنة.", "Discover Full Access and flexible ways to learn.")}</p></div><button onClick={() => setTab("programs")}>{t("اكتشف خياراتك", "Explore your options")}<Arrow size={18}/></button></section>
        </>}

        {tab === "programs" && <><section className="page-heading"><div className="eyebrow"><span/>LEARN YOUR WAY</div><h1>{t("طموحك كبير.", "Big ambitions.")} <span className="accent-word">{t("وطريقتك لك.", "Your own way.")}</span></h1><p>{t("نبدأ بمستواك وهدفك، ونلقى خطة تناسب يومك.", "Start with your level and goals. Find a plan that fits your life.")}</p></section><div className="program-grid">{knowledge?.programs.map((program,i) => <article className={`program-card ${i === 0 ? "featured" : ""}`} key={program.id}><div className="program-top"><span>{program.name}</span>{i===0 ? <Globe2 size={27}/> : <Headphones size={27}/>}</div><h2>{ar ? program.ar : program.en}</h2><p>{ar ? program.description_ar : program.description_en}</p><ul>{(ar ? program.features_ar : program.features_en).map(feature => <li key={feature}><Check size={17}/>{feature}</li>)}</ul><div className="pricing-note"><span>{t("خطة مصمّمة لك", "PERSONALIZED TO YOU")}</span><h3>{t("السعر حسب مستواك وهدفك", "A price based on your level and goals")}</h3></div><button className="program-cta" onClick={() => void sendChat(t(`أبي أعرف إذا خيار ${program.name} يناسبني. اسأليني عن هدفي ومستواي.`, `Help me decide if ${program.name} suits me. Ask about my goal and level.`))}>{t("خلّيني أساعدك تختار", "Let’s find your fit")}<Arrow size={18}/></button><a href={program.url} target="_blank" rel="noreferrer">{t("تفاصيل من الموقع الرسمي", "Details on the official website")}<Outward size={15}/></a></article>)}</div><div className="info-note"><CircleHelp size={21}/><p>{t("هذي خيارات تعلّم، مو باقات بأسعار ثابتة. المستشار يؤكّد السعر والمدة والتفاصيل بعد تقييم مستواك.", "These are learning options, not fixed-price packages. An advisor confirms pricing, duration and inclusions after assessing your level.")}</p></div></>}

        {tab === "centers" && <><section className="page-heading"><div className="eyebrow"><span/>{t("خطوتك الجاية، أقرب لك", "YOUR NEXT STEP, CLOSER TO HOME")}</div><h1>{t("نلتقي قريب.", "Find your people.")} <span className="accent-word">{t("ونتعلّم سوا.", "Learn together.")}</span></h1><p>{t("اكتشف بعض مراكزنا في السعودية، أو شوف الدليل الكامل.", "Explore a selection of Saudi centers, or visit the full directory.")}</p></section><div className="center-toolbar"><label className="search-box"><Search size={19}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder={t("ابحث بالمدينة أو اسم المركز…", "Search by city or center…")} aria-label={t("ابحث عن مركز", "Search centers")}/>{search && <button onClick={() => setSearch("")} aria-label={t("مسح البحث", "Clear search")}><X size={17}/></button>}</label><a className="directory-link" href="https://wallstreetenglish.edu.sa/institutes/" target="_blank" rel="noreferrer">{t("كل المراكز", "All centers")}<Outward size={17}/></a></div><div className="centers-grid">{knowledge?.centers.filter(c => `${c.name} ${c.name_en} ${c.city} ${c.city_en}`.toLowerCase().includes(search.toLowerCase())).map(center => <article className="center-card" key={center.name}><div className="center-city"><span><MapPin size={16}/>{ar ? center.city : center.city_en}</span><span>SAUDI ARABIA</span></div><h2>{ar ? center.name : center.name_en}</h2><p dir="rtl">{center.address}</p><a href={`tel:+966${center.phone.slice(1)}`}><Phone size={16}/><span dir="ltr">{center.phone}</span><Outward size={15}/></a></article>)}</div>{knowledge && !knowledge.centers.some(c => `${c.name} ${c.name_en} ${c.city} ${c.city_en}`.toLowerCase().includes(search.toLowerCase())) && <div className="empty-state"><MapPin size={32}/><h3>{t("ما لقينا المركز في هذي القائمة", "No matching center in this selection")}</h3><p>{t("جرّب اسم مدينة ثانية، أو افتح الدليل الكامل لكل المراكز.", "Try another city, or check the full official directory.")}</p></div>}<div className="info-note"><Globe2 size={20}/><p>{t("مو قريب من مركز؟ فيه خيار دراسة عن بُعد. أكّد المواعيد والتوفر مباشرة مع المركز قبل الزيارة.", "Not near a center? Explore remote learning. Confirm hours and availability directly before visiting.")}</p></div></>}
        {loadError && tab !== "home" && <div className="error-notice" role="alert">{t("تعذّر تحميل المعلومات.", "Could not load information.")}<button onClick={() => void loadKnowledge()}>{t("إعادة المحاولة", "Try again")}</button></div>}
        {!knowledge && !loadError && tab !== "home" && <div className="loading-state" role="status">{t("نجهّز لك المعلومات…", "Loading your options…")}</div>}
        <footer className="page-footer"><span>{t("معك من أول «هلا» إلى أول إنجاز.", "From your first hello to your next big moment.")} <Heart size={12}/></span><span>WALL STREET ENGLISH <i/> {t("نسخة تجريبية", "DEMO EXPERIENCE")}</span></footer>
      </main>
    </div>

    <nav className="mobile-nav" aria-label={t("التنقّل الرئيسي", "Main navigation")}>{nav.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={tab===item.id ? "selected" : ""}><item.icon size={21}/><span>{item.label}</span></button>)}<button onClick={() => setModal("settings")}><Settings2 size={21}/><span>{t("تفضيلاتي", "Preferences")}</span></button></nav>

    <dialog ref={dialog} className={`modal ${modal === "chat" || modal === "transcript" ? "chat-modal" : ""}`} onCancel={() => setModal(null)} onClick={event => { if (event.target === dialog.current) setModal(null); }} aria-labelledby="modal-title">
      <div className="modal-header"><div className="modal-hala-icon"><Wave small/></div><div><h2 id="modal-title">{modal === "settings" ? t("على راحتك", "Make it yours") : modal === "about" ? t("تعرّف على هلا", "Meet Hala") : modal === "transcript" ? t("نص المحادثة", "Your conversation") : t("سولف مع هلا", "Chat with Hala")}</h2><p>{t("رفيقتك بالذكاء الاصطناعي", "Your AI learning companion")}</p></div><button className="icon-button" onClick={() => setModal(null)} aria-label={t("إغلاق", "Close")}><X size={21}/></button></div>
      {modal === "chat" && <><div className="chat-content" role="log" aria-live="polite"><div className="chat-bubble assistant">{t("يا هلا! أنا هلا، مساعدتك بالذكاء الاصطناعي. وش ودّك نبدأ فيه اليوم؟", "Hi! I’m Hala, your AI learning guide. What would you like to work on today?")}</div>{messages.map((message,i) => <div key={i} className={`chat-bubble ${message.role}`} dir="auto">{message.content}</div>)}{chatBusy && <div className="typing" aria-label={t("هلا تكتب", "Hala is typing")}><i/><i/><i/></div>}{chatError && <div className="error-notice" role="alert">{chatError}</div>}<div ref={chatBottom}/></div><form className="chat-form" onSubmit={event => { event.preventDefault(); void sendChat(); }}><input autoComplete="off" maxLength={4000} aria-label={t("رسالتك لهلا", "Your message to Hala")} placeholder={t("اكتب اللي في بالك…", "What’s on your mind?")} value={draft} onChange={event => setDraft(event.target.value)}/><button disabled={chatBusy || !draft.trim()} aria-label={t("إرسال", "Send")}><Send size={20}/></button></form><p className="chat-privacy">{t("المحادثة مؤقتة. لا تشارك بيانات حساسة.", "This conversation is temporary. Don’t share sensitive information.")}</p></>}
      {modal === "transcript" && <div className="chat-content" role="log" aria-live="polite">{!voice.transcript.length && <div className="empty-state"><AudioLines size={32}/><p>{t("كلامك وكلام هلا يظهر هنا خلال المحادثة.", "Your conversation will appear here as you speak.")}</p></div>}{voice.transcript.map(item => <div key={item.id} className={`chat-bubble ${item.role}`} dir="auto">{item.text}</div>)}<div ref={chatBottom}/></div>}
      {modal === "settings" && <div className="modal-body"><h3>{t("لغة التجربة", "Experience language")}</h3><div className="language-options"><button className={ar ? "selected" : ""} onClick={() => { if (!ar) changeLanguage(); }}>العربية السعودية {ar && <Check size={17}/>}</button><button className={!ar ? "selected" : ""} onClick={() => { if (ar) changeLanguage(); }}>English {!ar && <Check size={17}/>}</button></div><p>{t("تغيير اللغة أثناء المكالمة ينهيها؛ تبدأ الجلسة الجاية باللغة الجديدة.", "Changing language during a call ends it. Your next session uses the new language.")}</p><h3>{t("صوت هلا", "Hala’s voice")}</h3><div className="voice-setting"><Volume2 size={20}/><div><strong>{t("دافئ. واضح. قريب منك.", "Warm. Clear. Here for you.")}</strong><p>{t("صوت أنثوي بالذكاء الاصطناعي، مع توجيه للهجة السعودية.", "An AI-generated feminine voice, guided to speak Saudi Arabic.")}</p></div></div><h3>{t("خصوصيتك", "Your privacy")}</h3><p>{t("الميكروفون يشتغل بس لما تبدأ المحادثة ويتوقف عند إنهائها. الصوت والنص يُرسلان إلى OpenAI للرد عليك. هذا التطبيق ما يحفظ تسجيلاتك أو محادثاتك؛ نحفظ تفضيلات اللغة والهدف على جهازك فقط.", "Your microphone starts only when you start a call and stops when you end it. Audio and text are sent to OpenAI to generate replies. This app does not save recordings or chats; only language and goal preferences stay on your device.")}</p></div>}
      {modal === "about" && <div className="modal-body"><span className="about-pill">SAY HELLO TO WHAT’S NEXT</span><h3>{t("يا هلا في خطوتك الجاية.", "Say hello to your next chapter.")}</h3><p>{t("هلا مساعدتك بالذكاء الاصطناعي في تجربة وول ستريت إنجلش السعودية. تساعدك تمارس الإنجليزية، تفهم خيارات الدراسة، وتلقى بداية تناسب طموحك.", "Hala is an AI guide in this Wall Street English Saudi Arabia demo. Practice English, understand your learning options, and find a first step that fits your ambitions.")}</p><p>{t("هذي تجربة توضيحية، ما تحجز مواعيد أو ترسل طلبات تسجيل. الأسعار والتوفر يؤكّدها مستشار المعهد.", "This is a demonstration. It does not book appointments or submit enrollment requests. An advisor confirms prices and availability.")}</p><div className="source-links"><h3>{t("معلومات من المصدر", "Information from the source")}</h3>{(knowledge?.sources || []).map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.title}<Outward size={15}/></a>)}<small>{t("آخر مراجعة للمعلومات: ", "Information reviewed: ")}{knowledge?.verified_at || "2026-09-14"}</small></div></div>}
    </dialog>
  </div>;
}
